### PR TITLE
Use a qualified RTEnv during expansion

### LINKED ISSUE #1761: [bug] unable to use a type alias spec of an inlined haskell function in a refined data type spec
**Problem:**
* Define and inline a predicate over a value.
* Create an alias as shorthand to express that the predicate is satisfied in a specification.
* Use the specification in a refined data type.
```haskell
{-@ inline oneFunPred @-}
oneFunPred :: Int -> Bool
oneFunPred x = x == 1

{-@ type OneTyAlias a = {v:a | oneFunPred v} @-}

{-@ data One = One { field :: OneTyAlias Int }  @-}
data One = One Int -- ERROR (ranjit said it ought to pass)
```
**Expect:**
The refined data type has a constructor with a specification requiring the predicate to be satisfied.
**Actual:**
Unbound symbol error on `oneFunPred` for the line with the data definition.
```
lib/Bug.hs:10:12: error:
    • Illegal type specification for `Bug.One`
    Bug.One :: Bug.field##Bug.One:{VV : GHC.Types.Int | Bug.oneFunPred VV} -> {VV : Bug.One | Bug.field VV == Bug.field##Bug.One
                                                                                              && Bug.field VV == Bug.field##Bug.One
                                                                                              && (is$Bug.One VV <=> true)}
    Sort Error in Refinement: {VV : int | Bug.oneFunPred VV}
    Unbound symbol Bug.oneFunPred --- perhaps you meant: Bug.field, Bug.One ?
    •
   |
10 | data One = One Int
   |            ^^^^^^^
```

---

**Workaround:**
Inline the type alias into the refined data type specification.
```haskell
{-@ inline oneFunPred @-}
oneFunPred :: Int -> Bool
oneFunPred x = x == 1

{-@ data One = One { field :: {v:Int | oneFunPred v}}  @-}
data One = One Int

-- This example passes (as expected)
```

**Version:**
Bug present in hackage releases
```
liquidhaskell 0.8.10.2
liquid-base 4.14.1.0
liquid-prelude 0.8.10.2
```
and also present in built-from-source
```
liquidhaskell@de4f003920d23a2683987c7f89db1afcf7df3b80 (Sept 16)
```

[Link to slack conv](https://liquidhaskell.slack.com/archives/C54QAL9RR/p1600451110042700)

### PR DESCRIPTION
**Pull request by adinapoli**
_Actually_ fixes #1761.

The problem was subtle. Let's consider again the test case for #1761:

```haskell
module T1761 where

{-@ inline oneFunPred @-}
oneFunPred :: Int -> Bool
oneFunPred x = x == 1

{-@ type OneTyAlias a = {v:a | oneFunPred v} @-}

{-@ data One = One { field :: OneTyAlias Int }  @-}
data One = One Int
```

What we want here is for LH to first _qualify_ everything and turn `type OneTyAlias a = {v:a | oneFunPred v} ` into `type OneTyAlias a = {v:a | T1761.oneFunPred v}` and then _expand_ everything in a way that `OneTyAlias` is expanded into `{v:a | T1761.oneFunPred v}` and then `T1761.oneFunPred` expanded into `v == 1`, yielding `{v:a | v == 1}`.

However, this wasn't working. Let's remember that a `BareRTEnv` is defined as:

```haskell
type BareRTEnv   = RTEnv Symbol BareType 
data RTEnv tv t = RTE
  { typeAliases :: M.HashMap Symbol (F.Located (RTAlias tv t))
  , exprAliases :: M.HashMap Symbol (F.Located (RTAlias Symbol Expr))
  }
```

The culprit was that the `Symbol` used as keys in the `HashMap` are always qualified, but the inner values were not. This means that when LH tried to expand `OneTyAlias`, it would look into `typeAliases`, find a match and replace this with
`{v:a | oneFunPred v}`. But this is wrong, because now when we try to expand `oneFunPred` by looking into the `exprAliases` `HashMap`, the lookup for `oneFunPred` will fail, because everything is keyed over a qualified `Symbol` (so we would have an entry in the map for `T1761.oneFunPred` but no entry for `oneFunPred`)!

The fix was to call `qualify` over the `(F.Located (RTAlias tv t))` of the `typeAliases` map, producing a new `RTEnv` to be passed to the call to `expand`.

### CODE REVIEW

File: src/Language/Haskell/Liquid/Bare.hs [hunk 1]
```diff
@@ -176,12 +176,12 @@ ghcSpecEnv sp = fromListSEnv binds
...
-                 , [(symbol v, vSort v) | v              <- gsReflects (_gsRefl sp)]
-                 , [(x,        vSort v) | (x, v)         <- gsFreeSyms (_gsName sp), Ghc.isConLikeId v ]
-                 , [(x, RR s mempty)    | (x, s)         <- wiredSortedSyms       ]
-                 , [(x, RR s mempty)    | (x, s)         <- _gsImps sp       ]
+                 [ [(x,        rSort t) | (x, Loc _ _ t)  <- gsMeas     (_gsData sp)]
+                 , [(symbol v, rSort t) | (v, Loc _ _ t)  <- gsCtors    (_gsData sp)]
+                 , [(symbol v, vSort v) | v               <- gsReflects (_gsRefl sp)]
+                 , [(x,        vSort v) | (x, v)          <- gsFreeSyms (_gsName sp), Ghc.isConLikeId v ]
+                 , [(x, RR s mempty)    | (x, s)          <- wiredSortedSyms       ]
+                 , [(x, RR s mempty)    | (x, s)          <- _gsImps sp       ]
```
Comment (adinapoli) [inline src/Language/Haskell/Liquid/Bare.hs:184]: Ups, this is a relic of my previous attempt. I can fix this after CI is fully green and the review is done, if that's bothering us.

**Comment by ranjitjhala** [comment]
thanks!!
