### PR TITLE
only rewrite casts that are actually constructing a dictionary

### LINKED ISSUE #598: Using GHC generics causes liquid haskell to panic
If I try to type-check this program:

```haskell
{-# LANGUAGE DeriveGeneric #-}

import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))

data Point = Point
    { x :: {-# UNPACK #-} !Int
    } deriving (Generic)

instance NFData Point
```

... it fails with a panic at the core extraction step:

```
**** DONE:  Extracted Core using GHC *******************************************
 
liquid: <no location info> Unexpected panic (!)
    (Another Broken Test!!!) splitc unexpected:
{lq_tmp$x##1409 : (Control.DeepSeq.GNFData (GHC.Generics.M1 GHC.Generics.D Main.D1Point (GHC.Generics.M1 GHC.Generics.C Main.C1_0Point (GHC.Generics.M1 GHC.Generics.S Main.S1_0_0Point (GHC.Generics.K1 GHC.Generics.R GHC.Types.Int))))) | lq_tmp$x##1409 == $dGNFData_a4BT}

lq_tmp$x##1391:(GHC.Generics.Rep Main.Point a) -> ()
gabriel@wind:~/proj/succinct-vector$ xsel --clipboard < test.hs
```

This occurs when deriving other classes, too, like `Binary`.

### PR DESCRIPTION
**Pull request by gridaphobe**
fixes #598

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Super thanks!!

File: src/Language/Haskell/Liquid/Constraint/Generate.hs [hunk 1]
```diff
@@ -1028,6 +1022,39 @@ castTy g t (Tick _ e)
 castTy _ _ e
   = panic Nothing $ "castTy cannot handle expr " ++ showPpr e
 
+isClassConCo :: Coercion -> Maybe (Expr Var -> Expr Var)
+-- See Note [Type classes with a single method]
```
Comment (gridaphobe) [inline src/Language/Haskell/Liquid/Constraint/Generate.hs]: @ranjitjhala @nikivazou GHC has this wonderful system of long-form comments in their source code that explain complicated checks and processes. It works as follows:

1. Write a self-contained comment describing at length the process, and give it a header

    ```
    -- Note [My complicated thing]
    -- details...
    ```

2. Reference `Note [My complicated thing]` at the relevant points of the implementation.

That's it! Now, someone else can come along, read the code, and grep for `Note [My complicated thing]` when they inevitably get confused.
